### ISSUE TITLE
BC5_SNORM Normal Map issue

### ISSUE THREAD

**Issue by GRY4096** [matyalatte/Blender-DDS-Addon#14]
BC5_SNORM Normals when imported into blender look different
original normal map
<img width="513" alt="Photoshop_2yyBWEhvvE" src="https://github.com/matyalatte/Blender-DDS-Addon/assets/54209267/baad0e52-1dcd-4e09-9536-cc28f0d28335">
after importing into blender
<img width="513" alt="AzO97iYdzN" src="https://github.com/matyalatte/Blender-DDS-Addon/assets/54209267/457f0a67-06b2-4afa-b6e3-1c37da30ab9d">

**Comment by matyalatte** [comment]
Hi, sorry for the late reply. I worked on other projects recently.
The issue was fixed at f8262bf8b0e0c3b270cf8060cfc855ecd2e73b2f.
You can see the original normal map when using sRGB as color space.
![snorm_issue_fixed](https://github.com/matyalatte/Blender-DDS-Addon/assets/69258547/8708e50e-79a6-4663-bbb8-bbfc5d1948b2)

I'll merge the fixed branch later.
(The testing workflow is broken due to updates of blender.org. I need to fix it before releasing the fixed version.)

If you want the fixed version right now, you can apply the commit by yourself.
Or use Github Actions to build the addon from the dev branch.
https://github.com/matyalatte/Blender-Uasset-Addon/wiki/How-to-Build-with-Github-Actions
