### ISSUE TITLE
Blender 4.2 Viewport "Material" Crash

### ISSUE THREAD

**Issue by Seris0** [matyalatte/Blender-DDS-Addon#26]
Hello, I'm still investigating, however, I couldn't find the answer as to why, in version 4.2, when importing DDS files and changing to viewport shading causes Blender to crash. The funny thing is that, it only happens if you do it in that order, if you clicked on shading first and then loaded the DDS files, the problem does not occur.

https://github.com/user-attachments/assets/387f45cb-fdef-48db-b4c1-b158cd5ab403

[blender.crash.txt](https://github.com/user-attachments/files/16228588/blender.crash.txt)

![Screenshot_2](https://github.com/user-attachments/assets/c02146d8-c9b5-4681-9b8c-a915188cddac)

**Comment by BujusKrachus** [comment]
Leaving a reference to the original report here: https://projects.blender.org/blender/blender/issues/124697

**Comment by matyalatte** [comment]
Thanks for the report. Confirmed it on my machine.
But I'm not sure if the cause is my addon or not. It works fine on old releases of Blender. And I know Blender had another issue that crashed third party addons before (https://projects.blender.org/blender/blender/issues/99900)

It is clear that the changes in Blender made this issue, but Idk if Blender should fix it or if I should fix my dll.

**Comment by matyalatte** [comment]
The cause was that `texconv.dll` changed the locale to the user's default value.
There are no crashes if I comment out the lines about `std::locale` in the DLL.

It is a bit odd that Blender does not use the user's default settings but it is undesirable for DLLs to change the locale. So, I will address this as a bug in the DLL.
I opened a new issue for it.
https://github.com/matyalatte/Texconv-Custom-DLL/issues/14

**Comment by Seris0** [comment]
For now, I figure out that the Release 0.3.5 version is stable in Blender 4.2 and does not cause any issues.

**Comment by matyalatte** [comment]
Fixed at https://github.com/matyalatte/Texconv-Custom-DLL/commit/f6fd36d45e338597f1bedd66f14b46e9f70e07cc.
